spring:
  application:
    name: payment-service
  data:
    mongodb:
      auto-index-creation: true
      uri: ${MONGO_URI}

  kafka:
    producer:
      acks: all
      retries: 10
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${TEMPO_ENDPOINT:http://tempo:4317}
LOKI_URL: ${LOKI_URL:-http://localhost:3100/loki/api/v1/push}

app:
  kafka:
    endpoint: ${KAFKA_ENDPOINT:localhost:9092}
  external-api:
    integer-generator-url: ${INTEGER_GENERATOR:https://www.random.org/integers/?num=1&min=1&max=100&col=1&base=10&format=plain&rnd=new}

security:
  constants:
    jwt:
      secret: ${JWT_SECRET}